### ISSUE TITLE
About front end source code

### ISSUE THREAD

**Issue by zhepoch** [google-ai-edge/model-explorer#75] opened 2024-06-03 10:06 UTC
Did we have a plan to publicize the model-explorer front-end angular source code?

**Comment by pkgoogle** [comment] 2024-06-03 17:05
Hi @zhepoch, would you say this is a duplicate of https://github.com/google-ai-edge/model-explorer/issues/47 ?

**Comment by zhepoch** [comment] 2024-06-04 03:09
Hi @pkgoogle, 
yes, it's a duplicate with #47, I followed #47 for several days, but no one responded, so I resubmitted one.

**Comment by pkgoogle** [comment] 2024-06-04 18:57
Hi @zhepoch, thanks for letting us know -- it is actually counter-productive for us to have duplicates so we will close this one for now, please follow progress on the other issue, thanks.

**Closed by pkgoogle** 2024-06-04 18:57 UTC
Labels: type:others
