### ISSUE TITLE
[Feature Request] Adding Metadata to layers

### ISSUE THREAD

**Issue by el-agua** [google-ai-edge/model-explorer#67] opened 2024-05-24 17:13 UTC
Would be nice to be able to add metadata directly to layers, the same way we can add attributes to input, output, and nodes themselves.

**Comment by pkgoogle** [comment] 2024-05-28 17:44
Hi @el-agua, would you say this is a duplicate of https://github.com/google-ai-edge/model-explorer/issues/48 ?

**Comment by el-agua** [comment] 2024-05-28 18:00
From my initial reading, I think it may be different? From my understanding, #48 refers to nodes, where I think it would be beneficial to add metadata to namespaces.

**Comment by pkgoogle** [comment] 2024-06-03 23:14
Thanks @el-agua, we're in the process of defining our roadmap and we'll keep this in mind.

**Comment by pkgoogle** [comment] 2024-06-13 21:14
Hi @el-agua, can you describe your use case a bit more elaborately -- we want to understand why you want this feature so that we may judge how important it is and how we may prioritize it.

**Comment by el-agua** [comment] 2024-06-14 14:03
We are trying to model systems. For example, a car would have nodes that model velocity, position, angular velocity, etc. However, the car itself would be a layer in this graph, and it would be nice to be able to store k/v pairs on that (make, model, etc).

**Comment by pkgoogle** [comment] 2024-06-21 21:57
Hi @el-agua,

Thank you for sharing your valuable feedback and use case with us. We appreciate your interest in this feature.

Currently, our focus is on enhancing the core machine learning capabilities of our platform. However, we're excited about the possibility of expanding our offerings in the future. Once our front-end becomes open source, we welcome any contributions you or any others would like to make in adding this functionality.

In the meantime, we'll keep your suggestion in mind as we plan for future enhancements. We appreciate your understanding and look forward to collaborating with the community.

**Comment by jinjingforever** [comment] 2024-08-26 18:29
Hi,

We've added the support in v0.1.10. Please give it a try:

- Add support for adding custom attributes to group/layer nodes.
    Use the new `groupNodeAttributes` field in `graph_builder.Graph`. Example:

    ```python
    graph = gb.Graph(id='graph',
                     nodes=[top_node, node0, node1, node2],
                     groupNodeAttributes={
                         # Use empty name for graph-level attributes.
                         '': {'model attr': 'value'},
                         'layer1': {'layer attr': 'value'}})
    ```
    ![graph node attributes](https://github.com/user-attachments/assets/90b8789d-f5e9-447a-b247-44d7404efdb6)

**Closed by jinjingforever** 2024-08-26 18:29 UTC
Labels: type:feature, stat:contribution welcome, front-end

**Comment by AllenFind** [comment] 2025-08-11 02:09
Hi @jinjingforever,

Looks like we need to put namespace into the groupNodeAttributes? If the we have layer2[layer1], we need to put 
```
'layer2/layer1': {'layer attr': 'value'}
```
I wonder how to decide the artificial layer when the graph is too large and we will have `section_1_of_6`.

thanks.
